# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build/Release

on:
  workflow_dispatch: # Allow manual triggering
  push:
    tags:
      - 'v*.*.*' # Trigger on pushing version tags

jobs:
  # Build the app
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            os-base: mac
          - os: ubuntu-latest
            os-base: linux
          - os: windows-latest
            os-base: windows

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version-file: 'go.mod'

    # Enable if tests are added
    # - name: Test
    #   run: go test -v ./...

    - name: Create bin directory
      run: mkdir -p build/bin

    - name: Create release directory
      run: mkdir -p release

    - name: Build
      run: go build -C ./cmd/zei -v

    - name: Copy to bin directory
      run: cp cmd/zei/zei** build/bin

    - name: Zip release file
      uses: vimtor/action-zip@v1.2
      with:
        files: build/bin
        recursive: false
        dest: release/zei_${{ matrix.os-base }}.zip

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: zei_${{ matrix.os-base }}
        path: release/
        retention-days: 7

  # Create a release
  release:
    if: startsWith(github.ref_name, 'v')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        path: release/
        merge-multiple: true

    - name: Release
      uses: softprops/action-gh-release@v2.0.6
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: true
        files: release/*
